name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  backend_install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install

  frontend_install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install

  deploy:
    needs: [backend_install, frontend_install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build backend Docker image
        run: docker build -t backend:latest ./backend
      - name: Build frontend Docker image
        run: docker build -t frontend:latest ./frontend
